# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file_tranfer_pb2 as file__tranfer__pb2


class FileTransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transfer = channel.stream_unary(
                '/FileTransfer/Transfer',
                request_serializer=file__tranfer__pb2.FileTransferRequest.SerializeToString,
                response_deserializer=file__tranfer__pb2.FileTransferResponse.FromString,
                )
        self.Process = channel.unary_stream(
                '/FileTransfer/Process',
                request_serializer=file__tranfer__pb2.FileMetaData.SerializeToString,
                response_deserializer=file__tranfer__pb2.ProcessingInfo.FromString,
                )
        self.Download = channel.unary_stream(
                '/FileTransfer/Download',
                request_serializer=file__tranfer__pb2.ProcessingMetaData.SerializeToString,
                response_deserializer=file__tranfer__pb2.FileDownloadResponse.FromString,
                )


class FileTransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transfer(self, request_iterator, context):
        """Send the file to the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Process(self, request, context):
        """Trigger the processing of the file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Download(self, request, context):
        """Get the processed results from the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transfer': grpc.stream_unary_rpc_method_handler(
                    servicer.Transfer,
                    request_deserializer=file__tranfer__pb2.FileTransferRequest.FromString,
                    response_serializer=file__tranfer__pb2.FileTransferResponse.SerializeToString,
            ),
            'Process': grpc.unary_stream_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=file__tranfer__pb2.FileMetaData.FromString,
                    response_serializer=file__tranfer__pb2.ProcessingInfo.SerializeToString,
            ),
            'Download': grpc.unary_stream_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=file__tranfer__pb2.ProcessingMetaData.FromString,
                    response_serializer=file__tranfer__pb2.FileDownloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileTransfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transfer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/FileTransfer/Transfer',
            file__tranfer__pb2.FileTransferRequest.SerializeToString,
            file__tranfer__pb2.FileTransferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileTransfer/Process',
            file__tranfer__pb2.FileMetaData.SerializeToString,
            file__tranfer__pb2.ProcessingInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileTransfer/Download',
            file__tranfer__pb2.ProcessingMetaData.SerializeToString,
            file__tranfer__pb2.FileDownloadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
